defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      TERM: xterm
      NPM_CONFIG_PREFIX: "~/.npm-global"

    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "esy.lock.json" }}-{{ checksum "package.json" }}-{{ checksum "tests/package.json" }}-{{ checksum "tests/yarn.lock" }}
      - run:
          name: Install esy
          command: |
            mkdir -p $NPM_CONFIG_PREFIX
            npm config set prefix $NPM_CONFIG_PREFIX
            eval "echo 'export PATH=$(npm -g bin):$PATH'" >> $BASH_ENV
            npm install -g esy

      - run:
          name: Install Dependencies
          command: |
            echo $PATH
            esy install
            cd tests && yarn install
      - run:
          name: Build and test
          command: |
            esy build

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "esy.lock.json" }}-{{ checksum "package.json" }}-{{ checksum "tests/package.json" }}-{{ checksum "tests/yarn.lock" }}
          paths:
            - ~/.esy
            - node_modules
            - test/node_modules
      - store_artifacts:
          path: _build/default/graphql_to_reason.exe
          destination: workspace/graphql_to_reason.exe
